import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0E1217] text-white"
        
      >
      <NavBar/>

      <main className="h-[80vh] mx-auto">
        {children}
      </main>
      <footer className="text-center w-full py-9">
        <h2>Professionally maximize interactive alignments rather than timely imperatives. Enthusiastically brand emerging e-business.</h2>
      </footer>
      </body>
    </html>
  );
}
